In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_excel('klasi.xlsx')
df

Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk Sesak Nafas  \
0       pr    50           155           56  tidak  tidak  tidak       tidak   
1       pr    31           154           60  tidak  tidak  tidak       tidak   
2       lk    32           163           56  tidak  tidak  tidak       tidak   
3       lk    21           165           53  tidak  tidak  tidak       tidak   
4       lk    33           166           62  tidak  tidak  tidak       tidak   
..     ...   ...           ...          ...    ...    ...    ...         ...   
243     pr    33           161           58     ya  tidak  tidak       tidak   
244     lk    29           164           59     ya  tidak  tidak       tidak   
245     lk    49           165           57     ya  tidak     ya       tidak   
246     pr    41           158           64  tidak  tidak  tidak       tidak   
247     lk    23           165           65  tidak  tidak  tidak       tidak   

    Keluhan Lain  Status  
0             ya       0  
1             ya       0  
2             ya       0  
3          tidak       0  
4             ya       0  
..           ...     ...  
243           ya       0  
244           ya       1  
245        tidak       1  
246           ya       0  
247           ya       0  

[248 rows x 10 columns]

In [3]:
df.isna().sum()

Gender          0
Umur            0
Tinggi Badan    0
Berat Badan     0
Pilek           0
Demam           0
Batuk           0
Sesak Nafas     0
Keluhan Lain    0
Status          0
dtype: int64

In [4]:
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Gender        248 non-null    object
 1   Umur          248 non-null    int64 
 2   Tinggi Badan  248 non-null    int64 
 3   Berat Badan   248 non-null    int64 
 4   Pilek         248 non-null    object
 5   Demam         248 non-null    object
 6   Batuk         248 non-null    object
 7   Sesak Nafas   248 non-null    object
 8   Keluhan Lain  248 non-null    object
 9   Status        248 non-null    int64 
dtypes: int64(4), object(6)
memory usage: 19.5+ KB


In [5]:
N, D = df.shape
print('N: %d, D: %d' %(N, D))

N: 248, D: 10


In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df['Gender'])
df['Pilek'] = encoder.fit_transform(df['Pilek'])
df['Demam'] = encoder.fit_transform(df['Demam'])
df['Batuk'] = encoder.fit_transform(df['Batuk'])
df['Sesak Nafas'] = encoder.fit_transform(df['Sesak Nafas'])
df['Keluhan Lain'] = encoder.fit_transform(df['Keluhan Lain'])

In [7]:
df

Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  \
0         1    50           155           56      1      0      0   
1         1    31           154           60      1      0      0   
2         0    32           163           56      1      0      0   
3         0    21           165           53      1      0      0   
4         0    33           166           62      1      0      0   
..      ...   ...           ...          ...    ...    ...    ...   
243       1    33           161           58      2      0      0   
244       0    29           164           59      2      0      0   
245       0    49           165           57      2      0      1   
246       1    41           158           64      1      0      0   
247       0    23           165           65      1      0      0   

     Sesak Nafas  Keluhan Lain  Status  
0              0             1       0  
1              0             1       0  
2              0             1       0  
3              0             0       0  
4              0             1       0  
..           ...           ...     ...  
243            0             1       0  
244            0             1       1  
245            0             0       1  
246            0             1       0  
247            0             1       0  

[248 rows x 10 columns]

In [8]:
def ubah(v):
    if v == 1:
        return 0
    else:
        return 1
df['Pilek'] = df.Pilek.apply(ubah)

def ganti(w):
    if w == 1:
        return 0
    else:
        return 1
df['Gender'] = df.Gender.apply(ganti)

In [9]:
df

Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  \
0         0    50           155           56      0      0      0   
1         0    31           154           60      0      0      0   
2         1    32           163           56      0      0      0   
3         1    21           165           53      0      0      0   
4         1    33           166           62      0      0      0   
..      ...   ...           ...          ...    ...    ...    ...   
243       0    33           161           58      1      0      0   
244       1    29           164           59      1      0      0   
245       1    49           165           57      1      0      1   
246       0    41           158           64      0      0      0   
247       1    23           165           65      0      0      0   

     Sesak Nafas  Keluhan Lain  Status  
0              0             1       0  
1              0             1       0  
2              0             1       0  
3              0             0       0  
4              0             1       0  
..           ...           ...     ...  
243            0             1       0  
244            0             1       1  
245            0             0       1  
246            0             1       0  
247            0             1       0  

[248 rows x 10 columns]

In [10]:
# Separating attributes
X = df[df.columns[:9]]

# Separating label
y = df['Status']

In [11]:
from sklearn.preprocessing import StandardScaler

# standardization of data set values
scaler = StandardScaler()


scaler.fit(X)
X = scaler.transform(X)

X

array([[-1.49022791,  1.5015217 , -1.90731934, ..., -0.37796447,
        -0.26261287,  0.46442036],
       [-1.49022791, -0.18786948, -2.20221659, ..., -0.37796447,
        -0.26261287,  0.46442036],
       [ 0.6710383 , -0.09895415,  0.4518587 , ..., -0.37796447,
        -0.26261287,  0.46442036],
       ...,
       [ 0.6710383 ,  1.41260637,  1.04165321, ...,  2.64575131,
        -0.26261287, -2.15322169],
       [-1.49022791,  0.70128377, -1.02262758, ..., -0.37796447,
        -0.26261287,  0.46442036],
       [ 0.6710383 , -0.89919208,  1.04165321, ..., -0.37796447,
        -0.26261287,  0.46442036]])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2)
print(X_train.shape, y_train.shape)

(186, 9) (186,)


In [13]:
print(X_test.shape, y_test.shape)

(62, 9) (62,)


In [14]:
from sklearn import svm
from sklearn.svm import SVC

# create SVC object and call fit function to train model
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [15]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [16]:
y_test

186    0
90     1
165    0
166    1
91     0
      ..
6      0
28     0
12     0
29     1
89     0
Name: Status, Length: 62, dtype: int64

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[45,  0],
       [ 4, 13]], dtype=int64)

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        45
           1       1.00      0.76      0.87        17

    accuracy                           0.94        62
   macro avg       0.96      0.88      0.91        62
weighted avg       0.94      0.94      0.93        62



In [19]:
from sklearn.model_selection import GridSearchCV

parameters = {
    'kernel' : ['rbf', 'poly', 'sigmoid'],
    'C' : [0.5, 1, 10, 100],
    'gamma' : ['scale', 1, 0.1, 0.01, 0.001]
}

grid_search = GridSearchCV(estimator=SVC(random_state=0),
                          param_grid=parameters,
                          n_jobs=6,
                          verbose=1,
                          scoring='accuracy')

grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


GridSearchCV(estimator=SVC(random_state=0), n_jobs=6,
             param_grid={'C': [0.5, 1, 10, 100],
                         'gamma': ['scale', 1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             scoring='accuracy', verbose=1)

In [20]:
print(f'Best Score: {grid_search.best_score_}')

best_params = grid_search.best_estimator_.get_params()
print(f'Best Parameters:')
for param in parameters:
    print(f'\t{param}: {best_params[param]}')

Best Score: 0.9088193456614511
Best Parameters:
	kernel: rbf
	C: 1
	gamma: 0.01


In [21]:
y_pred = grid_search.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        45
           1       1.00      0.76      0.87        17

    accuracy                           0.94        62
   macro avg       0.96      0.88      0.91        62
weighted avg       0.94      0.94      0.93        62

