In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_excel('klasifikasi.xlsx')
df.head()

Gender  Umur  Tinggi Badan  Berat Badan  Pilek  Demam  Batuk  Sesak Nafas  \
0       0    50           155           56      0      0      0            0   
1       0    31           154           60      0      0      0            0   
2       1    32           163           56      0      0      0            0   
3       1    21           165           53      0      0      0            0   
4       1    33           166           62      0      0      0            0   

   Keluhan Lain  Status  
0             1       0  
1             1       0  
2             1       0  
3             0       0  
4             1       0

In [3]:
df.isna().sum()

Gender          0
Umur            0
Tinggi Badan    0
Berat Badan     0
Pilek           0
Demam           0
Batuk           0
Sesak Nafas     0
Keluhan Lain    0
Status          0
dtype: int64

In [4]:
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gender        248 non-null    int64
 1   Umur          248 non-null    int64
 2   Tinggi Badan  248 non-null    int64
 3   Berat Badan   248 non-null    int64
 4   Pilek         248 non-null    int64
 5   Demam         248 non-null    int64
 6   Batuk         248 non-null    int64
 7   Sesak Nafas   248 non-null    int64
 8   Keluhan Lain  248 non-null    int64
 9   Status        248 non-null    int64
dtypes: int64(10)
memory usage: 19.5 KB


In [5]:
N, D = df.shape
print('N: %d, D: %d' %(N, D))

N: 248, D: 10


In [6]:
# Separating attributes
X = df[df.columns[:8]]

# Separating label
y = df['Status']

In [7]:
from sklearn.preprocessing import StandardScaler

# standardization of data set values
scaler = StandardScaler()


scaler.fit(X)
X = scaler.transform(X)

X

array([[-1.49022791,  1.5015217 , -1.90731934, ..., -0.38490018,
        -0.37796447, -0.27975144],
       [-1.49022791, -0.18786948, -2.20221659, ..., -0.38490018,
        -0.37796447, -0.27975144],
       [ 0.6710383 , -0.09895415,  0.4518587 , ..., -0.38490018,
        -0.37796447, -0.27975144],
       ...,
       [ 0.6710383 ,  1.41260637,  1.04165321, ..., -0.38490018,
         2.64575131, -0.27975144],
       [-1.49022791,  0.70128377, -1.02262758, ..., -0.38490018,
        -0.37796447, -0.27975144],
       [ 0.6710383 , -0.89919208,  1.04165321, ..., -0.38490018,
        -0.37796447, -0.27975144]])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2)
print(X_train.shape, y_train.shape)

(186, 8) (186,)


In [9]:
print(X_test.shape, y_test.shape)

(62, 8) (62,)


In [10]:
from sklearn import svm

# create SVC object and call fit function to train model
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [11]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [12]:
y_test

186    0
90     1
165    0
166    1
91     0
      ..
6      0
28     1
12     0
29     1
89     0
Name: Status, Length: 62, dtype: int64

In [13]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[45,  1],
       [ 4, 12]], dtype=int64)

In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        46
           1       0.92      0.75      0.83        16

    accuracy                           0.92        62
   macro avg       0.92      0.86      0.89        62
weighted avg       0.92      0.92      0.92        62

